import { Spec } from '@stellar/stellar-sdk/contract'

export enum Methods {
  deposit = 'deposit',
  withdraw = 'withdraw',
  getEstimatedYield = 'get_estimated_yield',
  getPosition = 'get_position',
  getEstimatedPrematureWithdraw = 'get_estimated_premature_withdraw',
  getTimeLeft = 'get_time_left',
  extendContractValidity = 'extend_contract_validity',
  initialize = 'initialize',
}

export const spec = new Spec([
  'AAAAAAAAAAAAAAAKaW5pdGlhbGl6ZQAAAAAACAAAAAAAAAAFYWRtaW4AAAAAAAATAAAAAAAAAAVhc3NldAAAAAAAABMAAAAAAAAABHRlcm0AAAAGAAAAAAAAAA1jb21wb3VuZF9zdGVwAAAAAAAABgAAAAAAAAAKeWllbGRfcmF0ZQAAAAAABgAAAAAAAAALbWluX2RlcG9zaXQAAAAACwAAAAAAAAAMcGVuYWx0eV9yYXRlAAAABgAAAAAAAAAQYWxsb3dhbmNlX3BlcmlvZAAAAAQAAAAA',
  'AAAAAAAAAAAAAAAHZGVwb3NpdAAAAAACAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAAB2FkZHJlc3MAAAAAEwAAAAA=',
  'AAAAAAAAAAAAAAAId2l0aGRyYXcAAAACAAAAAAAAAAdhZGRyZXNzAAAAABMAAAAAAAAAGWFjY2VwdF9wcmVtYXR1cmVfd2l0aGRyYXcAAAAAAAABAAAAAA==',
  'AAAAAAAAAAAAAAATZ2V0X2VzdGltYXRlZF95aWVsZAAAAAABAAAAAAAAAAdhZGRyZXNzAAAAABMAAAABAAAACw==',
  'AAAAAAAAAAAAAAAMZ2V0X3Bvc2l0aW9uAAAAAQAAAAAAAAAHYWRkcmVzcwAAAAATAAAAAQAAAAs=',
  'AAAAAAAAAAAAAAAgZ2V0X2VzdGltYXRlZF9wcmVtYXR1cmVfd2l0aGRyYXcAAAABAAAAAAAAAAdhZGRyZXNzAAAAABMAAAABAAAACw==',
  'AAAAAAAAAAAAAAANZ2V0X3RpbWVfbGVmdAAAAAAAAAEAAAAAAAAAB2FkZHJlc3MAAAAAEwAAAAEAAAAG',
  'AAAAAAAAAAAAAAAYZXh0ZW5kX2NvbnRyYWN0X3ZhbGlkaXR5AAAAAAAAAAA=',
  'AAAAAQAAAAAAAAAAAAAAC0RlcG9zaXREYXRhAAAAAAIAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAJdGltZXN0YW1wAAAAAAAABg==',
  'AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAACAAAAAAAAAAAAAAABUFkbWluAAAAAAAAAAAAAAAAAAAFQXNzZXQAAAAAAAAAAAAAAAAAAAxDb21wb3VuZFN0ZXAAAAAAAAAAAAAAAARUZXJtAAAAAAAAAAAAAAAJWWllbGRSYXRlAAAAAAAAAAAAAAAAAAAKTWluRGVwb3NpdAAAAAAAAAAAAAAAAAALUGVuYWx0eVJhdGUAAAAAAQAAAAAAAAAHRGVwb3NpdAAAAAABAAAAEw==',
])
